### Springboot configuration
server.port=21119


### web3Sdk configuration
#是否使用国密用户
encrypt-type=0

#GroupChannelConnectionsConfig 配置待连接的群组，可以配置一个或多个群组，每个群组需要配置群组ID
#GroupChannelConnectionsConfig配置 证书
#1.把证书放在resource目录下的conf中
#2.注意这里要添加classpath:
group-channel-connections-config.caCert=classpath:conf/ca.crt
group-channel-connections-config.sslCert=classpath:conf/sdk.crt
group-channel-connections-config.sslKey=classpath:conf/sdk.key
#节点所属的群组
group-channel-connections-config.all-channel-connections[0].group-id=1
#每个群组可以配置一个或多个节点，设置群组节点的配置文件config.ini中[rpc]部分的channel_listen_ip(若节点小于v2.3.0版本，查看配置项listen_ip)和channel_listen_port。
group-channel-connections-config.all-channel-connections[0].connections-str[0]=192.168.13.135:20200
group-channel-connections-config.all-channel-connections[0].connections-str[1]=192.168.13.135:20201

# sdk实际连接的群组
channel-service.group-id=1

#指定操作智能合约的账号私钥
#注意要提前创建好账号
account-config.private-key=aeed0683be93b0d30cffcd5c2a6214eb9f3cf9ce5faa5f15bec44228c26c442a


### JavaSdk configuration
#证书配置
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.7.0/docs/sdk/java_sdk/configuration.html#id5
java-sdk.cryptoMaterial.certPath=conf

#节点配置
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.7.0/docs/sdk/java_sdk/configuration.html#id6
java-sdk.network.peers[0]=192.168.13.135:20202
java-sdk.network.peers[1]=192.168.13.135:20203

#部署用户的身份
#注意不要用引号
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.7.0/docs/sdk/java_sdk/configuration.html#id9
java-sdk.account.accountFilePath=javaSdk/account/0x8424e4028c49c6377588521f892d7f03c2d36e77.pem
#保存生成的用户pem文件位置
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.7.0/docs/sdk/java_sdk/key_tool.html#id6
#java-sdk.account.keyStoreDir=account

#自定义配置 sdk要连接的groupid
java-sdk.connect-group-id=1

#合约的地址
#注意要提前在群组中部署合约
contractAddress= 0x768edbc739b0469cb025c8cfe8ba932509b029e5