### Springboot configuration
server.port=21119


### web3Sdk configuration
#是否使用国密用户
encrypt-type=0
#GroupChannelConnectionsConfig配置 证书
group-channel-connections-config.caCert=classpath:conf/ca.crt
group-channel-connections-config.sslCert=classpath:conf/sdk.crt
group-channel-connections-config.sslKey=classpath:conf/sdk.key
#GroupChannelConnectionsConfig 连接的group配置
group-channel-connections-config.all-channel-connections[0].group-id=1
group-channel-connections-config.all-channel-connections[0].connections-str[0]=192.168.13.135:20200
group-channel-connections-config.all-channel-connections[0].connections-str[1]=192.168.13.135:20201
# sdk实际连接的群组
channel-service.group-id=1
#指定部署的用户私钥
account-config.private-key=aeed0683be93b0d30cffcd5c2a6214eb9f3cf9ce5faa5f15bec44228c26c442a


### JavaSdk configuration
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.7.0/docs/sdk/java_sdk/configuration.html#id12
java-sdk.cryptoMaterial.certPath=conf
java-sdk.network.peers[0]=192.168.13.135:20202
java-sdk.network.peers[1]=192.168.13.135:20203
#部署用户的身份
java-sdk.accountFilePath="javaSdk/account/0x8424e4028c49c6377588521f892d7f03c2d36e77.pem"
#自定义配置 sdk要连接的groupid
java-sdk.connect-group-id=1

#合约的地址
contractAddress= 0x91df002233479603166f045440e0c3799ad56f69